// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function Check(arg1) {
  return window['go']['main']['App']['Check'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function ExportDevices() {
  return window['go']['main']['App']['ExportDevices']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetNetworkAdapters() {
  return window['go']['main']['App']['GetNetworkAdapters']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportDevices() {
  return window['go']['main']['App']['ImportDevices']();
}

export function OnReady() {
  return window['go']['main']['App']['OnReady']();
}

export function Remote(arg1, arg2) {
  return window['go']['main']['App']['Remote'](arg1, arg2);
}

export function SaveDeviceList(arg1) {
  return window['go']['main']['App']['SaveDeviceList'](arg1);
}

export function ScanNetwork() {
  return window['go']['main']['App']['ScanNetwork']();
}

export function SetSchedule(arg1, arg2) {
  return window['go']['main']['App']['SetSchedule'](arg1, arg2);
}

export function UpdateDevice(arg1, arg2) {
  return window['go']['main']['App']['UpdateDevice'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function Wake(arg1) {
  return window['go']['main']['App']['Wake'](arg1);
}

export function WakeAll() {
  return window['go']['main']['App']['WakeAll']();
}
