// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDevice(arg1:main.Device):Promise<main.Response>;

export function Check(arg1:number):Promise<void>;

export function DeleteDevice(arg1:number):Promise<main.Response>;

export function ExportDevices():Promise<main.Response>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetSettings():Promise<main.Settings>;

export function ImportDevices():Promise<main.ImportResult>;

export function OnReady():Promise<void>;

export function Remote(arg1:number,arg2:string):Promise<void>;

export function SaveDeviceList(arg1:Array<main.Device>):Promise<main.Response>;

export function ScanNetwork():Promise<void>;

export function SetSchedule(arg1:number,arg2:main.Schedule):Promise<main.Response>;

export function UpdateDevice(arg1:number,arg2:main.Device):Promise<main.Response>;

export function Version():Promise<string>;

export function Wake(arg1:number):Promise<void>;

export function WakeAll():Promise<void>;
